### ISSUE TITLE
Typo that bugs

### ISSUE THREAD

**Issue by objmagic** [janestreet/rpc_parallel#1]
https://github.com/janestreet/rpc_parallel/blob/master/_oasis#L39

`rpc_parallel_core` should be `rpc_parallel.core`

**Comment by dxue2012** [comment]
Any updates on this? I'm getting the same issue when trying to compile the library.

> ocamlfind: Package 'rpc_parallel_core' not found - required by 'rpc_parallel'

and `ocamlfind list | grep -i rpc_parallel` gives

```
rpc_parallel        (version: 112.35.00)
rpc_parallel.core   (version: 112.35.00)
```

**Comment by ghost** [comment]
Indeed, thanks! We'll do a minor release soon.
