### ISSUE TITLE
How do I create a worker in a remote server?

### ISSUE THREAD

**Issue by wu-s-john** [janestreet/rpc_parallel#4]
I have been trying to find an easy way to spawn a worker that I have implemented on a remote server. The closest examples that I have seen to accomplish this is [`number_stats.ml`](https://github.com/janestreet/rpc_parallel/blob/master/example/number_stats.ml) and [`server.ml`](https://github.com/janestreet/rpc_parallel/blob/master/example/serve.ml). However, I having trouble doing so.

For the `number_stats.ml` example, I was wondering what is the processes to set up a remote worker. I was wondering if I need to deploy a server that implements the function, `Generate_random_map_function`. What command line inputs did you guys use for `remote-host` and `remote-path`?

I tried to create a spawn a remote worker in my local host using the following method:

      Rpc_worker.spawn_exn 
        ~on_failure:Error.raise
        ~shutdown_on:Heartbeater_timeout 
        ~redirect_stdout:`Dev_null
        ~redirect_stderr:`Dev_null ~name:(sprintf "Server %d" id) {id; state}
        ~where:(Rpc_parallel.Executable_location.Remote (Rpc_parallel.Remote_executable.existing_on_host
                        ~executable_path:"foo.exe"
                        "127.0.0.1"))

However, I got the following error.
```
(monitor.ml.Error
 ("Process.run failed"
  ((prog ssh) (args (127.0.0.1 md5sum ./server.exe))
   (exit_status (Exit_non_zero 255)) (stdout "")
   (stderr ("ssh: connect to host 127.0.0.1 port 22: Connection refused\r" ""))))
 ("Raised at file \"src/import0.ml\" (inlined), line 351, characters 22-32"
  "Called from file \"src/error.ml\" (inlined), line 9, characters 14-30"
  "Called from file \"src/or_error.ml\", line 74, characters 17-32"
  "Called from file \"src/deferred1.ml\", line 20, characters 40-45"
  "Called from file \"src/job_queue.ml\", line 159, characters 6-47"))
```
Obviously, I cannot connect to `127.0.0.1` because port 22 is not exposed. How would I be able to spawn a remote worker using `spawn_exn`?

**Comment by yminsky** [comment]
Addressed here: https://discuss.ocaml.org/t/how-do-you-create-a-remote-workers-with-rpc-parallel/2353
