### ISSUE TITLE
Bidirectional rpc?

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [janestreet/rpc_parallel#9]
I wonder if it is possible to make a bidirectional pipe that is a combination of `create_pipe` and `create_reverse_pipe`. That is, I'm looking for a function with the signature
```
val create_bidirection_pipe
    :  ?name:string
    -> f:
         (worker_state:worker_state
          -> conn_state:connection_state
          -> 'query
          -> 'update Pipe.Reader.t
          -> 'response Pipe.Reader.t Deferred.t)
    -> bin_query:'query Bin_prot.Type_class.t
    -> bin_update:'update Bin_prot.Type_class.t
    -> bin_response:'response Bin_prot.Type_class.t
    -> unit
    -> (worker, 'query * 'update Pipe.Reader.t, 'response Pipe.Reader.t) _function
```
Is this already possible with the current `rpc_parallel`? If not, can such a function be added?

Thanks for making this package available!

**Comment by jakemcarthur** [comment]
I doubt we will have the spare time to implement this right now, but it's doable and seems like a perfectly reasonable feature to have. If you were to make a pull request that includes a working demonstration in the `example` directory then I think we'd be pretty likely to accept it. I think the implementation should be quite similar to the existing reverse pipe implementation. Anyway, for now I will close this.

You could instead use `create_pipe` and `create_reverse_pipe` together to achieve the same affect without modifying the library, although you may have to do a little bookkeeping to relate the two dispatches appropriately on the worker side, similar to what the library already does for you with reverse pipes.
